Arithmetic Operation

In [ ]:
r = 1500
t = 0.2

total = r * (1+t)
total

1800.0

In [ ]:
2**3

8

In [ ]:
2!=3

True

And or Not

In [ ]:
(10>5) or (10<5)

True

In [ ]:
(10>5) and (10<5)

False

List

In [23]:
l = [10,20,30,40]
l

[10, 20, 30, 40]

In [12]:
l.append (50)
l

[10, 20, 30, 40, 50]

In [24]:
l[0] = 11
l

[11, 20, 30, 40]

In [13]:
l = [10,'test1234', 'mest', [40,10], 123]
l

[10, 'test1234', 'mest', [40, 10], 123]

In [15]:
l[0]

10

In [16]:
l[-1]

123

In [17]:
len(l)

5

In [18]:
l = [10, 'test', 'mest', 40]
l

[10, 'test', 'mest', 40]

In [23]:
l[-2]

'mest'

In [19]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

Tuple

In [20]:
t = (10, 12, 13)

Set

In [26]:
my_list = [1, 2, 3, 4, 5, 5, 5, 5, 5,5]
my_list

[1, 2, 3, 4, 5, 5, 5, 5, 5, 5]

In [27]:
my_set = set (my_list)
my_set

{1, 2, 3, 4, 5}

In [30]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

In [31]:
a.intersection(b)

{4, 5}

Dictionary

In [32]:
# key value pairs
customers = {
            'Alice': 25,
            'Bob': 30,
            'Charlie': 35
            }

In [35]:
customers['Alice']=30

In [37]:
customers

{'Alice': 30, 'Bob': 30, 'Charlie': 35}

In [54]:
customer = {'name': 'Alice', 'age': 30, 'city':'New York'}
customer['State'] ='NY'
customer['Segment'] ='Premium'

In [56]:
customer1 = customer
customer1

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [57]:
#Bob
customer2 = {'name': 'Bob', 'age': 25, 'city':'Los Angeles', 'State': 'CA', 'Segment':'Standard'}

In [72]:
#Armen
customer3 = {'name': 'Charlie', 'age': 28, 'city':'Chicago', 'State': 'IL'}

In [73]:
list_of_customers = [customer1, customer2, customer3]

In [74]:
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standard'},
 {'name': 'Charlie', 'age': 28, 'city': 'Chicago', 'State': 'IL'}]

In [77]:
list_of_customers[0].keys()

dict_keys(['name', 'age', 'city', 'State', 'Segment'])

In [78]:
l = [10,20,30,40]
d = {'key', 'Value'}

Pandas

In [92]:
import pandas as pd

In [185]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'Armen', 'David'],
        'age': [30, 25, 28, 35, 42],
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard','Premium']}

In [148]:
data ['name']
data ['age']

[30, 25, 28, 35, 42]

In [186]:
df = pd.DataFrame(data)

In [181]:
df_filtered=df[df['age']>30]
df_filtered

    name  age           city
3  Armen   35         Boston
4  David   42  San Francisco

In [190]:
df.loc[df['revenue']>15000, 'segment']='High Revenue'

In [191]:
df.head()

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000       Premium
2  Charlie   28        Chicago    12000       Premium
3    Armen   35         Boston    20000  High Revenue
4    David   42  San Francisco    18000  High Revenue