Arithmetic Operation

In [ ]:
r = 1500
t = 0.2

total = r * (1+t)
total

1800.0

In [ ]:
2**3

8

In [ ]:
2!=3

True

And or Not

In [ ]:
(10>5) or (10<5)

True

In [ ]:
(10>5) and (10<5)

False

List

In [23]:
l = [10,20,30,40]
l

[10, 20, 30, 40]

In [12]:
l.append (50)
l

[10, 20, 30, 40, 50]

In [24]:
l[0] = 11
l

[11, 20, 30, 40]

In [13]:
l = [10,'test1234', 'mest', [40,10], 123]
l

[10, 'test1234', 'mest', [40, 10], 123]

In [15]:
l[0]

10

In [16]:
l[-1]

123

In [17]:
len(l)

5

In [18]:
l = [10, 'test', 'mest', 40]
l

[10, 'test', 'mest', 40]

In [23]:
l[-2]

'mest'

In [19]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

Tuple

In [20]:
t = (10, 12, 13)

Set

In [26]:
my_list = [1, 2, 3, 4, 5, 5, 5, 5, 5,5]
my_list

[1, 2, 3, 4, 5, 5, 5, 5, 5, 5]

In [27]:
my_set = set (my_list)
my_set

{1, 2, 3, 4, 5}

In [30]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

In [31]:
a.intersection(b)

{4, 5}

Dictionary

In [32]:
# key value pairs
customers = {
            'Alice': 25,
            'Bob': 30,
            'Charlie': 35
            }

In [35]:
customers['Alice']=30

In [37]:
customers

{'Alice': 30, 'Bob': 30, 'Charlie': 35}

In [54]:
customer = {'name': 'Alice', 'age': 30, 'city':'New York'}
customer['State'] ='NY'
customer['Segment'] ='Premium'

In [56]:
customer1 = customer
customer1

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [57]:
#Bob
customer2 = {'name': 'Bob', 'age': 25, 'city':'Los Angeles', 'State': 'CA', 'Segment':'Standard'}

In [72]:
#Armen
customer3 = {'name': 'Charlie', 'age': 28, 'city':'Chicago', 'State': 'IL'}

In [73]:
list_of_customers = [customer1, customer2, customer3]

In [74]:
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standard'},
 {'name': 'Charlie', 'age': 28, 'city': 'Chicago', 'State': 'IL'}]

In [77]:
list_of_customers[0].keys()

dict_keys(['name', 'age', 'city', 'State', 'Segment'])

In [78]:
l = [10,20,30,40]
d = {'key', 'Value'}

Pandas

In [92]:
import pandas as pd

In [185]:
data = {'name': ['Alice', 'Bob', 'Charlie', 'Armen', 'David'],
        'age': [30, 25, 28, 35, 42],
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard','Premium']}

In [148]:
data ['name']
data ['age']

[30, 25, 28, 35, 42]

In [186]:
df = pd.DataFrame(data)

In [181]:
df_filtered=df[df['age']>30]
df_filtered

    name  age           city
3  Armen   35         Boston
4  David   42  San Francisco

In [190]:
df.loc[df['revenue']>15000, 'segment']='High Revenue'

In [191]:
df.head()

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000       Premium
2  Charlie   28        Chicago    12000       Premium
3    Armen   35         Boston    20000  High Revenue
4    David   42  San Francisco    18000  High Revenue

If

In [1]:
revenue = 150

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

High revenue

In [4]:
revenue = 90

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

Normal revenue

In [7]:
revenue = 120
print("Analysis complete")
if revenue > 100:
    print("High revenue")
    print(f"Because the revenue is {revenue}")
else:
    print("low revenue")

Analysis complete
High revenue
Because the revenue is 120

In [13]:
revenue = 210

if revenue > 200:
    print(f"Very high revenue: {revenue}")
elif revenue > 100:
    print(f"High revenue: {revenue}")
elif revenue > 50:
    print(f"Medium revenue: {revenue}")
else:
    print(f"Low revenue: {revenue}")

Very high revenue: 210

In [14]:
b = 5
a = 6

In [16]:
a = b
a

5

In [17]:
a == b

True

In [19]:
revenue = 150
is_active = True

if revenue > 100 and True:
    print("Target customer")

Target customer

In [20]:
if is_active:
    print("Customer is active")

Customer is active

In [21]:
is_active = False

if not is_active:
    print("Customer is inactive")

Customer is inactive

Swap a & b

In [22]:
a = 6
b = 5

In [23]:
c = a
a = b
b = c

In [31]:
print (a)

5

In [32]:
print (b)

6

In [33]:
a = a + b

In [34]:
b = a - b
a = a - b

In [39]:
print (f" a is equal to: {a} \n b is equal to: {b}")

 a is equal to: 6
 b is equal to: 5

Loops

In [40]:
list_of_data_sources = ['data1.csv', 'data2.csv', 'data3,csv' ]

In [43]:
for i in list_of_data_sources:
    print(f'then name of current data source is: {i}')
print ('Exit loop')

then name of current data source is: data1.csv
then name of current data source is: data2.csv
then name of current data source is: data3,csv
Exit loop

In [44]:
number_of_clicks = 0

for i in range(5):
    number_of_clicks = i + 1

number_of_clicks

5

In [45]:
sales = [100, 200, 150]

total = 0

for value in sales:
    total = total + value

total

450

In [47]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)
    else:
        print("low sale:" , value)

low sale: 100
High sale: 200
High sale: 150
low sale: 50

In [49]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [50]:
customer.keys()
customer['name']

'Anna'

In [51]:
customer['city']

'Yerevan'

In [52]:
customer['revenue']

150

In [29]:
customer = {
    "name": ["Anna", "Gagik"],
    "revenue": [150, 200],
    "city": ["Yerevan", "Avan"]
}

customer
customer.keys()
customer.values()

dict_values([['Anna', 'Gagik'], [150, 200], ['Yerevan', 'Avan']])

In [30]:
customer.items()

dict_items([('name', ['Anna', 'Gagik']), ('revenue', [150, 200]), ('city', ['Yerevan', 'Avan'])])

In [31]:
for key, value in customer.items():
    print(key, ":", customer[key])

name : ['Anna', 'Gagik']
revenue : [150, 200]
city : ['Yerevan', 'Avan']

In [32]:
list(customer.values())[0]

['Anna', 'Gagik']

In [33]:
type(customer.values())

dict_values

In [34]:
customer.items()

dict_items([('name', ['Anna', 'Gagik']), ('revenue', [150, 200]), ('city', ['Yerevan', 'Avan'])])

In [36]:
for key,value in customer.items():
    print (key)
    print(key, ":", customer[key][1])

name
name : Gagik
revenue
revenue : 200
city
city : Avan

In [37]:
l = [10, 20, 30, 40, 50]

In [38]:
for i in range(len(l)):
    print(l[i])

10
20
30
40
50

In [39]:
for i in l[3:]:
    print(i)

40
50

In [40]:
l[:3]

[10, 20, 30]

In [23]:
t = ('name', 'Anna')