Installing Packages

In [109]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

Importing the Data

In [110]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [111]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [112]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [113]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['Excel', 'SQL'], dtype='str')
(21, 2)

   Excel      SQL
0      1   frozen
1      2    other
2      3   bakery
3      4  produce
4      5  alcohol

In [114]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

Working with 'Orders'

In [115]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [116]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [117]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

Q1: How many unique orders exist?

In [118]:
df_orders["order_id"].nunique()

3421083

In [119]:
df_orders.shape

(3421083, 7)

In [120]:
## Consistency Check: Order ID
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

Q2: How many distinct customers are represented in the dataset?

In [121]:
df_orders["user_id"].nunique()

206209

In [122]:
df_orders["order_id"].nunique()/df_orders["user_id"].nunique()

16.590367054784224

Q3: Exploring the eval_set distribution

In [123]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [124]:
df_dow = df_orders["order_dow"].value_counts().reset_index()
df_dow

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
3          5  453368
4          6  448761
5          3  436972
6          4  426339

In [125]:
df_dow.sort_values('order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [126]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [127]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [128]:
#import sys
#print(sys.executable)

In [129]:
#!pip show openpyxl

In [130]:
#!pip install openpyxl

In [131]:
df_ohod.to_excel('../data/processed/ohod.xlsx', index = False)

In [132]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [133]:
needed_columns = ['days_since_prior_order', 'order_number', 'user_id']

In [134]:
#df_orders[['days_since_prior_order', 'order_number']].head()
#df_first_orders = df_orders[needed_columns][df_orders['order_number'] == 1]
#print(df_first_orders.head())
#df_first_orders.reset_index(inplace=True)
#df_first_orders.head()

In [135]:
df_first_orders = df_orders[needed_columns][df_orders['order_number'] == 1].reset_index()
#df_first_orders.drop(columns='index', inplace=True)
df_first_orders = df_first_orders.drop(columns='index')

In [136]:
df_orders.iloc[26]

order_id                  1374495
user_id                         3
eval_set                    prior
order_number                    1
order_dow                       1
order_hour_of_day              14
days_since_prior_order        NaN
Name: 26, dtype: object

In [137]:
if df_orders["order_id"].is_unique:
    print('Happy')

Happy

In [138]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [139]:
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

In [140]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [141]:
df_orders_train.shape

(131209, 7)

In [142]:
# Since the further analysis is going to be done based on the subset where eval_set == 'Train'
#del df_orders

In [143]:
df_orders_products_train["reordered"].value_counts(normalize=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [144]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [145]:
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [146]:
10 > 8 > 3

True

In [147]:
atr = 8/10
atr

0.8

In [148]:
br = 3/10
br

0.3

In [149]:
df_orders_products_train.head(10)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1
5         1       13176                  6          0
6         1       47209                  7          0
7         1       22035                  8          1
8        36       39612                  1          0
9        36       19660                  2          1

In [150]:
df_orders_products_train["order_id"].is_unique

False

In [151]:
#add to cart order is one
df_orders_first_atc = df_orders_products_train[df_orders_products_train['add_to_cart_order']==1]
df_orders_first_atc.shape

(131209, 4)

In [152]:
df_orders_first_atc['product_id'].value_counts()

product_id
24852    4605
13176    3889
27845    1144
47766     995
21137     900
         ...
7044        1
28344       1
40866       1
13539       1
40800       1
Name: count, Length: 17908, dtype: int64

In [153]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [154]:
df_products.shape

(49693, 5)

In [155]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.9 MB

In [156]:
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,693.00 49,693.00      49,693.00 49,693.00
mean    24,844.35     67.77          11.73      9.99
std     14,343.72     38.32           5.85    453.52
min          1.00      1.00           1.00      1.00
25%     12,423.00     35.00           7.00      4.10
50%     24,845.00     69.00          13.00      7.10
75%     37,265.00    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [157]:
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [158]:
df_products[df_products['product_name'].isna()==True]

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14   12.20
68             69          NaN        26              7   11.80
115           116          NaN        93              3   10.80
261           262          NaN       110             13   12.10
525           525          NaN       109             11    1.20
1511         1511          NaN        84             16   14.30
1780         1780          NaN       126             11   12.30
2240         2240          NaN        52              1   14.20
2586         2586          NaN       104             13   12.40
3159         3159          NaN       126             11   13.10
3230         3230          NaN       120             16   14.40
3736         3736          NaN        41              8   14.80
4283         4283          NaN        77              7   14.40
4790         4790          NaN        91             16   14.50
38187       38183          NaN        39             12   20.90
40444       40440          NaN       120             16   14.80

In [159]:
#24852  - Banana
df_products[df_products['product_id'] == 24852]

       product_id product_name  aisle_id  department_id  prices
24853       24852       Banana        24              4   12.30

In [160]:
#13176 - Bag of Organic Bananas
df_products[df_products['product_id'] == 13176]

       product_id            product_name  aisle_id  department_id  prices
13176       13176  Bag of Organic Bananas        24              4   10.30

In [161]:
# max price
df_products.sort_values(by='prices', ascending=False).head(1)

       product_id           product_name  aisle_id  department_id    prices
33666       33664  2 % Reduced Fat  Milk        84             16 99,999.00

In [162]:
df_products["product_id"].nunique()

49686

In [163]:
df_products.shape
# we have duplicates

(49693, 5)

In [164]:
df_departments.head()
# somewhere we changed the columns name, but the Excel = department_id and SQL = department

   Excel      SQL
0      1   frozen
1      2    other
2      3   bakery
3      4  produce
4      5  alcohol

In [165]:
df_departments = df_departments.rename(columns={
    'Excel': 'department_id',
    'SQL': 'department'
})

In [166]:
df_departments.shape

(21, 2)

In [167]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [168]:
df_aisles.shape

(134, 2)

In [169]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [170]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [ ]:
#pd.merge(left_df, right_df, on="key_column", how="left")
df_products_aisles = pd.merge(df_products, df_aisles,
                              on="aisle_id",
                              how="left", indicator=True)

In [172]:
df_products_aisles.head()

,product_id,product_name,aisle_id,department_id,prices,aisle,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes,both
1,2,All-Seasons Salt,104,13,9.30,spices seasonings,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals,both
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation,both

In [173]:
print(df_products_aisles.columns)

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices',
       'aisle', '_merge'],
      dtype='str')

In [174]:
print(df_departments.columns)

Index(['department_id', 'department'], dtype='str')

In [193]:
df_products_aisles['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [ ]:
df_products_aisles_department = pd.merge(df_products_aisles, df_departments, 
                                         on='department_id',
                                         how='left')

In [196]:
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,_merge,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,both,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,both,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,both,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,both,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,both,pantry

In [ ]:
#df_products_aisles_department.drop(columns = ['aisle_id', 'department_id'], inplace=True)
#df_products_aisles.drop(columns = ['_merge'])

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation
...,...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.30,spirits
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.10,frozen vegan vegetarian
49690,49686,Artisan Baguette,112,3,7.80,bread
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.70,cat food care
49692,49688,Fresh Foaming Cleanser,73,11,13.50,facial care

In [207]:
df_products_aisles_department.drop(columns = ['_merge'], inplace=True)

In [208]:
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,pantry

In [ ]:
#del df_departments
#del df_products
#del df_aisles

In [210]:
df_products_aisles_department['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [213]:
import pandas as pd
URL_CUSTOMERS = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv'
URL_STATES = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv'

In [218]:
URLS = {
    'customers.csv': URL_CUSTOMERS,
    'state.csv': URL_STATES}

In [219]:
for i in URLS.items():
    print(f'file name {i[0]} \n file path: {i[1]}')

file name customers.csv
 file path: https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv
file name state.csv
 file path: https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv

In [220]:
for i in URLS.items():
    print(f'Downloading {i[0]}')
    df = pd.read_csv(i[1])
    df.to_csv(f'../data/downloads/{i[0]}')
    print(f'saving {i} in [../data/downloads]')

print('The job is done')

Downloading customers.csv
saving ('customers.csv', 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv') in [../data/downloads]
Downloading state.csv
saving ('state.csv', 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv') in [../data/downloads]
The job is done

In [215]:
df_customers = pd.read_csv(URL_CUSTOMERS)
df_customers.shape

(206209, 10)

In [217]:
df_customers.to_csv('../data/raw/customer.csv')