Dates

In [1]:
from datetime import datetime, date, timedelta

In [2]:
my_date = date(year=2026, month=4, day=25)

In [3]:
type(my_date)

datetime.date

In [4]:
my_time = datetime(year=2026, month=4, day=25, hour=14)

In [5]:
my_time

datetime.datetime(2026, 4, 25, 14, 0)

In [6]:
today = date.today()
today

datetime.date(2026, 5, 4)

In [7]:
now = datetime.now()
now

datetime.datetime(2026, 5, 4, 21, 32, 36, 12638)

In [8]:
my_date.strftime("%Y-%m-%d")

'2026-04-25'

In [9]:
my_date.strftime("%Y/%m/%d")

'2026/04/25'

In [10]:
my_date.strftime("%B %d, %Y")

'April 25, 2026'

In [11]:
start_date = my_date
end_date = date(2026,6,6)

In [12]:
delta = end_date - my_date
delta

datetime.timedelta(days=42)

In [13]:
end_date + timedelta(weeks=1)

datetime.date(2026, 6, 13)

In [16]:
rd = (today + timedelta(days=5)).strftime("%b %d %y")
rd

'May 09 26'

In [15]:
user = 'Davit'
email_content = f"""Dear {user},

Please find the attached report.
Kindly note that the reporting date is {rd}

Best regards,
Ani
"""

email_content

'Dear Davit,\n\nPlease find the attached report.\nKindly note that the reporting date is May 09 26\n\nBest regards,\nAni\n'

Dates with Pandas

In [17]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [19]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes

In [22]:
df_dates['signup_date'] = pd.to_datetime(df_dates['signup_date'])
df_dates['last_purchase'] = pd.to_datetime(df_dates['last_purchase'])

In [23]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [26]:
df_dates.to_csv('../data/test.csv', index=False)

In [27]:
test = pd.read_csv('../data/test.csv', parse_dates=['signup_date',
                                                  'last_purchase'],
                                                  dtype={'customer_id':str})
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      str
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 267.0 bytes

In [32]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [64]:
#df_dates["signup_date_name"] = df_dates['signup_date'].dt.month_name()
df_dates["signup_month_name"] = df_dates['signup_date'].dt.month_name()
df_dates["signup_day_name"] = df_dates['signup_date'].dt.day_name()
df_dates["days_count"] = df_dates['signup_date'].dt.days_in_month
df_dates["signup_dow"] = df_dates['signup_date'].dt.dayofweek

In [61]:
df_dates = df_dates.drop(columns=['signup_date_name'])

In [62]:
df_dates = df_dates.drop(columns=['days_in_month'])

In [65]:
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,days_count,signup_dow
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,31,0
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,29,1
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,31,1
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,31,0
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,30,2

In [71]:
df_dates["is_weekend"] = (df_dates['signup_date'].dt.day_of_week>=5).astype(int)

In [73]:
df_dates['days_between_signup_purchase'] = (df_dates['last_purchase'] - df_dates['signup_date']).dt.days

In [76]:
df_dates[df_dates['signup_date']>='2023']

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,days_count,signup_dow,is_weekend,days_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,31,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,29,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,31,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,31,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,30,2,0,93

In [79]:
df_dates.sort_values('signup_date')

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,days_count,signup_dow,is_weekend,days_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,31,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,29,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,31,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,31,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,30,2,0,93

In [80]:
df_dates.sort_values('signup_date', ascending=False)

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,days_count,signup_dow,is_weekend,days_between_signup_purchase
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,30,2,0,93
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,31,0,0,112
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,31,1,0,118
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,29,1,0,116
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,31,0,0,138

In [82]:
list(pd.date_range(start="2024-07-01", periods=7, freq="D"))

[Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-07-02 00:00:00'),
 Timestamp('2024-07-03 00:00:00'),
 Timestamp('2024-07-04 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-06 00:00:00'),
 Timestamp('2024-07-07 00:00:00')]

In [83]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [84]:
df_dates['bom'] = df_dates['signup_date'].dt.to_period('M').dt.start_time
df_dates['eom'] = df_dates['signup_date'].dt.to_period('M').dt.end_time

In [87]:
df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date

0    2024-01-01
1    2024-02-01
2    2024-03-01
3    2024-03-01
4    2024-04-01
Name: signup_date, dtype: object