In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from utils import csv_downloader

In [14]:
df_orders = csv_downloader(URL = 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/rfm/orders.csv',
                    name = 'orders',
                    path = '../data/rfm')

orders have been successfully saved in ../data/rfm
The size of the data (4906, 3)

In [26]:
df_orders.head()

           customer_id  order_date  revenue
0  Mr. Brion Stark Sr.  2004-12-20       32
1       Ethyl Botsford  2005-05-02       36
2       Hosteen Jacobi  2004-03-06      116
3        Mr. Edw Frami  2006-03-15       99
4          Josef Lemke  2006-08-14       76

In [28]:
df_orders = pd.read_csv('../data/rfm/orders', parse_dates = ['order_date'])

RFM

In [21]:
fig = px.histogram(data_frame=df_orders,
             x = 'revenue',
             title = 'Revenue Distribution',
             nbins = 40
             )
fig.update_layout(
    xaxis_title = 'Revenue',
    yaxis_title = 'Count'
)
fig.show()

# **RFM**

1. max_date()>Recency
2. max_date - customer last day
3. count()-frequency
4. SUM revenue

In [32]:
max_date = df_orders['order_date'].max()

In [33]:
rfm = df_orders.groupby('customer_id').agg(
    {'order_date':lambda date:(max_date - date.max()).days,
     'customer_id': lambda num: len(num),
     'revenue': lambda rev: rev.sum()
     }
)

```sql
--the same example with SQL,
SELECT
    customer_id,
    COUNT(customer_id) as Frequency
    max_date - max(order_date) as order_date,
    SUM(revenue) as revenue
FROM df_orders
GROUP BY customer_id;
````

In [36]:
# rfm.rename({})
column_names = ['Recency', 'Frequency', 'Monetary']
rfm.columns = column_names

rfm.head()

                    Recency  Frequency  Monetary
customer_id
Abbey O'Reilly DVM      204          6       472
Add Senger              139          3       340
Aden Lesch Sr.          193          4       405
Admiral Senger          131          5       448
Agness O'Keefe           89          9       843

In [37]:
rfm.reset_index(inplace = True)

In [38]:
rfm.head()

          customer_id  Recency  Frequency  Monetary
0  Abbey O'Reilly DVM      204          6       472
1          Add Senger      139          3       340
2      Aden Lesch Sr.      193          4       405
3      Admiral Senger      131          5       448
4      Agness O'Keefe       89          9       843